---
title: "Epi 560 Lab 4"
author: "Aileen Andrade-Torres"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:   
  html_document:
        df_print: paged
        theme: cosmo
        toc: yes
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "build") })
---

```{r SQL connection, echo=FALSE}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(knitr)
library(DBI) #load package 


#connect SQL
db <- dbConnect(RSQLite::SQLite(), dbname = "/Users/aileenandrade/Desktop/Spring/epi560lab/Andrade-Torres_A_epi560/epi560.sqlite")

sleepHead <- dbGetQuery(db, "SELECT * from P_HDL") #step 2

sleepHead

##### Column names are SEQN, LBDHDD, and LBDHDDSI

#step 3 

sleepHead2 <- dbGetQuery(db, "SELECT * from P_HDL LIMIT 3")

sleepHead2

##### Vaues for the first three rows for LBDHDD are 72, 56, and 47

#step 4 
dbDisconnect(db)


```

#Part 2
```{r Part 2}

# connect to SQL
db <- dbConnect(RSQLite::SQLite(), dbname = "/Users/aileenandrade/Desktop/Spring/epi560lab/Andrade-Torres_A_epi560/epi560.sqlite")

#pulling audiometry table 
audioTable <- dbGetQuery(db, "SELECT * from P_AUQ")

audioTable

#### column names
names(audioTable)

#### Var types 

sapply(audioTable, class)

## step 3 
#### based on NHANES code book SEQN is the primary key 

##Step 4 
#### there are no foreign keys for this table. NHANES folds foreign keys within
#### the SEQN key 

##Step 5: pulling Questionnaire: alcohol use table
alcUse <- dbGetQuery(db, "SELECT * from P_ALQ")

#### print only frist 5 row using kable
kable(head(alcUse, 5))

##Step 6

#### pull 2 coolumns from alcohol use table
sql_query <- "SELECT ALQ121, ALQ270 FROM P_ALQ;"

####execute query 
sub_alc_df <- dbGetQuery(db, sql_query)

####display first 5 rows
kable(head(sub_alc_df, 5))

##Step 7

#### Pulling two columns with one filtered condition
sql_query2 <- sql_query <- paste("SELECT ALQ121, ALQ270",
                    "FROM P_ALQ",
                    "WHERE ALQ121 > 4")
####execute query
sub_alc_df2 <- dbGetQuery(db, sql_query2)

####display first 5 rows
kable(head(sub_alc_df2, 5))

##Step 8
#### Pulling two columns with one filtered condition
sql_query3 <- sql_query <- paste("SELECT ALQ121, ALQ270",
                    "FROM P_ALQ",
                    "WHERE ALQ121 < 4 AND ALQ121 > 2")
####execute query
sub_alc_df3 <- dbGetQuery(db, sql_query3)

####display first 5 rows
kable(head(sub_alc_df3, 5))
```

##Part 3
```{r Joins, echo=FALSE}
####join two tables on SEQN-primary key
dem_alc_join <- paste(
  "SELECT *",
  "FROM P_ALQ",
  "LEFT JOIN P_DEMO ON P_ALQ.SEQN = P_DEMO.SEQN"
)

####execute query
joined_df <- dbGetQuery(db, dem_alc_join)

####display first 5 rows
kable(head(joined_df, 5))


#end session

dbDisconnect(db)

```
\pagebreak  

## Code Appendix  
 
```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE} 
```